version: '3.9'
services:
  db:
    image: postgres:17.5
    ports:
      - "5432:5432"
    env_file:
      - .env
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: